name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: namazudatte
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4   # ✅ versi terbaru
        with:
          name: snake
          path: dist/snake.svg

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4   # ✅ versi terbaru
        with:
          name: snake
          path: dist

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
